eslint-functional/eslint-plugin-functional

- CHANGELOG.md
- README.md
- docs/user-guide/migrating-from-tslint.md
- package.json
- src/util/rule.ts
Fixes #17.
This PR renames the package to eslint-plugin-functional and updates the readme to reflect that there are more rules than immutability.
Also adds a placeholder for #33.
> Rename the package

- docs/rules/immutable-data.md
- src/common/ignore-options.ts
- tests/common/ignore-options.test.ts
- tests/rules/immutable-data.test.ts
Fixes #46
BREAKING CHANGE: `ignoreAccessorPattern` now matching the property name as well as the object name. Likewise with `ignorePattern`.
> Text matching of MemberExpression nodes now includes the property name

- src/util/typeguard.ts
> fix(typeguards): only assume types if type information is not avaliable

- docs/rules/functional-parameters.md
- src/configs/all.ts
- src/configs/currying.ts
- src/configs/external-recommended.ts
- src/configs/functional-lite.ts
- src/configs/functional.ts
- src/configs/no-exceptions.ts
- src/configs/no-mutations.ts
- src/configs/no-object-orientation.ts
- src/configs/no-statements.ts
- src/util/misc.ts
- tests/configs.test.ts
- tests/helpers/util.ts
BREAKING CHANGE: The lite ruleset now behaves differently
fix #79
> Do not enforce a parameter count by default in the lite ruleset

- docs/rules/prefer-readonly-type.md
- src/rules/prefer-readonly-type.ts
- tests/rules/prefer-readonly-type.test.ts
Hello! I'm currently migrating the main frontend repo for my company from a tslint / eslint hybrid to pure eslint. In our old config, we were using tslint-immutable's `readonly-keyword` to enforce use of `readonly` for our interfaces. However, we never enabled the `readonly-array` rule. Now that we're migrating to eslint-plugin-functional, we're getting a huge number of linting errors from the `prefer-readonly-type` rule since it appears to be a union of these two rules from tslint-immutable. While some of these are auto-fixable, many are not and fixing them manually would be too large of an undertaking for us right now.
To remedy this, I propose adding an `ignoreMutableCollections` option to this rule that allows users to disable checks against Arrays, Tuples, Maps, and Sets. This will …
> Add ignoreMutableCollections option to prefer-readonly-type rule

- src/rules/prefer-type-literal.ts
replaced by @typescript-eslint/consistent-type-definitions
fix #170
> fix(prefer-type-literal): deprecated rule

- README.md
- docs/rules/functional-parameters.md
- docs/rules/immutable-data.md
- docs/rules/no-expression-statement.md
- docs/rules/no-let.md
- docs/rules/no-loop-statement.md
- docs/rules/no-promise-reject.md
- docs/rules/no-return-void.md
- docs/rules/options/allow-local-mutation.md
- docs/rules/options/ignore-pattern.md
- docs/rules/prefer-tacit.md
- docs/user-guide/migrating-from-tslint.md
- src/util/conditional-imports/typescript.ts
- src/util/typeguard.ts
Fixes: –
Mostly touched Markdown files. Did not touch the changelog.
Not sure about the word "stylitic." Is it intentional or should it be "stylistic" (notice the second "s")? _Stylitic_ is an adjective form of [_stylite_, which means "a Christian ascetic living atop a pillar."](https://www.merriam-webster.com/dictionary/stylite) Anyway, changing this might be a breaking change because the `stylitic` ruleset would need to be renamed, so it would be better to do it in a separate PR.
> docs: fix typos and capitalization of words

- .eslintrc.json
- .github/workflows/ci.yml
- package.json
- rollup.config.js
- src/common/ignore-options.ts
- src/rules/immutable-data.ts
- src/rules/no-conditional-statement.ts
- src/rules/prefer-readonly-type.ts
- src/util/rule.ts
- tests/common/ignore-options.test.ts
- tests/helpers/util.ts
- yarn.lock
BREAKING CHANGE: Node 12.4.0 or new is now required
> chore: update minimum required node version to 12

- src/rules/prefer-readonly-type.ts
- tests/rules/prefer-readonly-type.test.ts
> fix(prefer-readonly-type): allow inline mutable return types

- src/rules/no-method-signature.ts
- src/util/tree.ts
- src/util/typeguard.ts
- tests/rules/no-method-signature.test.ts
> feat(no-method-signature): properly handle `Readonly<{TSMethodSignature}>`

- docs/rules/immutable-data.md
Reading this doc made me think it wasn't including the situation where `delete` was used to remove an array element - which does not update the array's length which is often unexpected. However, trying it, it does flag this as an error, so I think it would be useful to have it in the docs.
```
3:1  error  Modifying an existing object/array is not allowed  functional/immutable-data
```
Maybe it could use to more explanation, but I'm not sure where that would do in this document.
Fixes: #(Issue Number)
> docs: add example of deleting an array element

- docs/rules/no-conditional-statement.md
- Minor typos helps the documentation flow.
- Remove implied reference to the option being described, helps readability. Less text more clarity.
- Wrap reserved keywords in code backticks.
> fix: typos and tighten a sentence

- .github/workflows/labels.yml
- .github/workflows/release.yml
- .releaserc
- README.md
Changes configs to use "main" branch over "master".
Once merged, the default branch needs to be changed to "main" in the repo's settings. The master branch can then be delete.
@jonaskello Can you merge this and make that settings change?
> chore: master => main

- package.json
- src/rules/prefer-tacit.ts
- tests/rules/prefer-tacit/index.test.ts
- tests/rules/prefer-tacit/ts/invalid.ts
- tests/rules/prefer-tacit/ts/valid.ts
- tests/rules/prefer-tacit/ts4.7/index.ts
- tests/rules/prefer-tacit/ts4.7/invalid.ts
- tests/rules/prefer-tacit/ts4.7/valid.ts
- tests/rules/prefer-tacit/tsNot4.7/index.ts
- tests/rules/prefer-tacit/tsNot4.7/invalid.ts
- tests/rules/prefer-tacit/tsNot4.7/valid.ts
- yarn.lock
As discussed in #405, this PR extends the autofixer of `prefer-tacit`, so that function calls with type parameters get transformed to instantiation expressions.
For example:
```ts
function createMyEventEmitter() {
return createEventEmitter<MyEventMapping>();
}
```
gets transformed to
```ts
const createMyEventEmitter = createEventEmitter<MyEventMapping>;
```
> feat(prefer-tacit): support autofixing function calls with type parameters

- docs/rules/functional-parameters.md
- src/common/ignore-options.ts
- src/rules/functional-parameters.ts
- src/util/rule.ts
- tests/rules/functional-parameters/es3/invalid.ts
- tests/rules/functional-parameters/es3/valid.ts
- tests/rules/functional-parameters/es6/valid.ts
re #207
re #244
This allows for ignoring functions where one of the given selectors matches the parent node in the AST of the function's node.
For more information see [ESLint Selectors](https://eslint.org/docs/developer-guide/selectors).
Example:
With the following config:
```json
{
"enforceParameterCount": "exactlyOne",
"ignorePrefixSelector": "CallExpression[callee.property.name='reduce']"
},
```
The following inline callback won't be flaged:
```js
const sum = [1, 2, 3].reduce(
(carry, current) => carry + current,
0
);`,
```
> feat(functional-parameters): add support for ignoring selector prefixes

- src/configs/recommended.ts
- src/rules/type-declaration-immutability.ts
- tests/rules/type-declaration-immutability/ts/invalid.ts
- tests/rules/type-declaration-immutability/ts/valid.ts
`RegExp` doesn't get handle correctly by eslint
> fix(type-declaration-immutability): only allow strings to be given for identifiers

- README.md
- docs/rules/prefer-immutable-types.md
- src/rules/prefer-immutable-types.ts
- tests/rules/prefer-immutable-types/ts/parameters/invalid.ts
- tests/rules/prefer-immutable-types/ts/return-types/invalid.ts
- tests/rules/prefer-immutable-types/ts/variables/invalid.ts
BREAKING CHANGE: The fixer config no longer inherits as many options as before; be sure to be
explicit in your configs.
fix #576
> feat(prefer-immutable-types)!: use suggestions instead of a fixer by default

- src/utils/misc.ts
- src/utils/type-guards.ts
- tests/rules/prefer-immutable-types/ts/variables/valid.ts
The `ignoreNamePattern` in `prefer-immutable-types` does not work with private class variables, but it should.
> fix(prefer-immutable-types): support private identifier

- src/rules/immutable-data.ts
- tests/rules/immutable-data/ts/array/invalid.ts
- tests/rules/immutable-data/ts/array/valid.ts
> fix(immutable-data): treat Object.entries({}).sort() as immediate mutation

- docs/rules/no-mixed-types.md
- src/rules/no-mixed-types.ts
- src/utils/type-guards.ts
- tests/rules/no-mixed-type/ts/invalid.ts
- tests/rules/no-mixed-type/ts/valid.ts
> fix(no-mixed-types): handle more than just property signatures, check the type of type references

- docs/rules/immutable-data.md
- src/rules/immutable-data.ts
- src/utils/tree.ts
- tests/rules/immutable-data/ts/object/invalid.ts
- tests/rules/immutable-data/ts/object/valid.ts
> feat(immutable-data): add option for `ignoreNonConstDeclarations` to `treatParametersAsConst`

- src/rules/prefer-tacit.ts
- src/utils/rule.ts
- tests/rules/prefer-tacit/ts/invalid.ts
> fix(prefer-tacit): handling functions that don't map to directly to an eslint node

- docs/rules/prefer-tacit.md
- src/rules/prefer-tacit.ts
- tests/rules/prefer-tacit/ts/invalid.ts
- tests/rules/prefer-tacit/ts/valid.ts
> fix(prefer-tacit): don't check member functions by default

- src/rules/no-conditional-statements.ts
- src/utils/type-guards.ts
Handle labeled break statements and continue statements in switch cases in the no-conditional-statements rule.
> fix(no-conditional-statements): allow continue and break statements with labels to be considered "returning"

- src/utils/misc.ts
- src/utils/type-guards.ts
- tests/rules/immutable-data/ts/object/valid.ts
> fix(immutable-data): ignoreAccessorPattern can now handle NonNullExpressions and ChainExpressions

- README.md
- docs/rules/functional-parameters.md
- knip.jsonc
- src/rules/functional-parameters.ts
- src/utils/schemas.ts
- tests/rules/functional-parameters.test.ts
> feat(functional-parameters): allow overriding options based on where the function type is declared

- docs/rules/prefer-immutable-types.md
- eslint.config.js
- src/rules/prefer-immutable-types.ts
> feat(prefer-immutable-types): allow overriding options based on where the type is declared

- docs/rules/no-throw-statements.md
- docs/rules/prefer-immutable-types.md
- eslint.config.js
- src/configs/recommended.ts
- src/rules/no-throw-statements.ts
- src/utils/tree.ts
- tests/rules/no-throw-statements.test.ts
> feat(no-throw-statements)!: replace option `allowInAsyncFunctions` with `allowToRejectPromises`

- docs/rules/no-classes.md
- src/rules/no-classes.ts
- tests/rules/__snapshots__/no-classes.test.ts.snap
- tests/rules/no-classes.test.ts
> feat(no-classes): add options ignoreIdentifierPattern and ignoreCodePattern

- .github/workflows/semantic-pr.yml
- README.md
- docs/rules/no-class-inheritance.md
- eslint.config.js
- src/configs/lite.ts
- src/rules/index.ts
- src/rules/no-class-inheritance.ts
- tests/rules/__snapshots__/no-class-inheritance.test.ts.snap
- tests/rules/no-class-inheritance.test.ts
> feat: new rule no-class-inheritance

- README.md
The current links reference moved markdown files in the typescript-eslint repo.
> docs: update typescript-eslint links

- src/utils/misc.ts
BREAKING CHANGE: when using patterns to match against PrivateIdentifiers, their names are now prefixed with a #.
fix #910 fix #911
> fix: prefix PrivateIdentifier names with a #

- docs/rules/immutable-data.md
- src/options/ignore.ts
- src/rules/immutable-data.ts
- src/utils/misc.ts
- src/utils/type-guards.ts
- tests/rules/immutable-data/__snapshots__/map.test.ts.snap
- tests/rules/immutable-data/__snapshots__/set.test.ts.snap
- tests/rules/immutable-data/map.test.ts
- tests/rules/immutable-data/set.test.ts
BREAKING CHANGE: map and set mutations will now be reported
fix #934
> feat(immutable-data): add support for detecting map and set mutations

- src/rules/no-throw-statements.ts
Previously, the rule `functional/no-throw-statements` did not declare `requiresTypeChecking: true`, which caused runtime errors when using it with `@typescript-eslint` without a `parserOptions.project` set.
This change adds `requiresTypeChecking: true` to the rule's meta to align with its actual type-dependent behavior.
> fix: mark no-throw-statements rule as requiring type checking
