- package.json
- src/common/ignore-options.ts
- src/util/typeguard.ts
- tests/common/ignore-options.test.ts
- tests/util.ts
- yarn.lock
Improves matching and adds a test.
> Ignore option fix

- src/rules/no-let.ts
- src/util/tree.ts
- src/util/typeguard.ts
- src/util/types.d.ts
- tests/rules/no-let.test.ts
> Remove no-let fixer

- src/rules/readonly-keyword.ts
- src/util/typeguard.ts
- tests/rules/readonly-keyword.test.ts
Fixes https://github.com/jonaskello/tslint-immutable/issues/145
> feat(readonly-keyword) Add support for parameter properties

- .eslintrc
- README.md
- docs/rules/prefer-type.md
- src/common/ignore-options.ts
- src/configs/all.ts
- src/configs/functional-lite.ts
- src/rules/index.ts
- src/rules/prefer-type.ts
- src/util/conditional-imports/.eslintrc
- tests/rules/prefer-type.test.ts
> new rule: prefer-type

- docs/rules/functional-parameters.md
- src/rules/functional-parameters.ts
- src/util/tree.ts
- src/util/typeguard.ts
- tests/rules/functional-parameters.test.ts
> feat(functional-parameters): Add option to allow iifes

- src/rules/functional-parameters.ts
- src/rules/immutable-data.ts
- src/rules/no-class.ts
- src/rules/no-conditional-statement.ts
- src/rules/no-expression-statement.ts
- src/rules/no-let.ts
- src/rules/no-loop-statement.ts
- src/rules/no-method-signature.ts
- src/rules/no-mixed-type.ts
- src/rules/no-reject.ts
- src/rules/no-return-void.ts
- src/rules/no-this.ts
- src/rules/no-throw.ts
- src/rules/no-try.ts
- src/rules/prefer-readonly-type.ts
- src/rules/prefer-type-literal.ts
- src/util/rule.ts
- tests/helpers/util.ts
Makes creating rules a little nicer.
> Refactor out the checkNode function for createRule.

- docs/rules/no-try.md
- src/rules/no-try.ts
- tests/rules/no-try.test.ts
> feat(no-try): Add options allowCatch and allowFinally.

- src/common/ignore-options.ts
- src/rules/immutable-data.ts
- src/util/typeguard.ts
- tests/rules/functional-parameters.test.ts
- tests/rules/immutable-data.test.ts
- tests/rules/prefer-readonly-type.test.ts
> Ignore Pattern Improvements

- docs/rules/immutable-data.md
- src/rules/immutable-data.ts
- tests/rules/immutable-data.test.ts
> fix(immutable-data): Implement option ignoreImmediateMutation

- README.md
👋Hello! This updates the docs for #66.
> docs(readme): change tslint-immutable to eslint-plugin-functional #66

- src/rules/no-expression-statement.ts
- src/util/misc.ts
- tests/rules/no-expression-statement.test.ts
> feat(no-expression-statement): allow specifying directive prologues

- src/configs/all.ts
- src/rules/index.ts
no-mixed-type replaced it
Fixes #82
> no-mixed-interface rule does not exist anymore

- src/common/ignore-options.ts
- src/util/tree.ts
- tests/rules/prefer-readonly-type.test.ts
> Local mutation in a function now only refers to within the function's body

- .eslintrc
- .travis.yml
- package.json
- src/util/typeguard.ts
- tests/common/ignore-options.test.ts
- tests/helpers/util.ts
- tests/index.test.ts
- tests/rules/functional-parameters.test.ts
- tests/rules/immutable-data.test.ts
- tests/rules/no-class.test.ts
- tests/rules/no-conditional-statement.test.ts
- tests/rules/no-expression-statement.test.ts
- tests/rules/no-let.test.ts
- tests/rules/no-loop-statement.test.ts
- tests/rules/no-method-signature.test.ts
- tests/rules/no-mixed-type.test.ts
- tests/rules/no-promise-reject.test.ts
- tests/rules/no-return-void.test.ts
- tests/rules/no-this-expression.test.ts
- tests/rules/no-throw-statement.test.ts
- tests/rules/no-try-statement.test.ts
- tests/rules/prefer-readonly-type.test.ts
- tests/rules/prefer-type-literal.test.ts
- test the index file
- test in an environment where TS is not installed
> Additional tests

- docs/rules/functional-parameters.md
- docs/rules/immutable-data.md
- docs/rules/no-class.md
- docs/rules/no-conditional-statement.md
- docs/rules/no-expression-statement.md
- docs/rules/no-let.md
- docs/rules/no-loop-statement.md
- docs/rules/no-method-signature.md
- docs/rules/no-mixed-type.md
- docs/rules/no-promise-reject.md
- docs/rules/no-return-void.md
- docs/rules/no-this-expression.md
- docs/rules/no-throw-statement.md
- docs/rules/no-try-statement.md
- docs/rules/options/allow-local-mutation.md
- docs/rules/options/ignore-pattern.md
- docs/rules/prefer-readonly-type.md
- docs/rules/prefer-type-literal.md
This PR adds examples of correct/incorrect code for each rule in the same style other eslint rules are done.
> Examples of correct/incorrect code for each rule

- README.md
Just found your repo and happened to notice this typo in the README. I am looking forward to trying out these ESLint rules; thanks :-).
> Fix URL to ESLint prefer-const rule

- src/rules/immutable-data.ts
- tests/rules/immutable-data.test.ts
> fix(immutable-data): add support for ignoring exceptions for update expressions

- src/rules/prefer-readonly-type.ts
- tests/rules/prefer-readonly-type.test.ts
> fix(prefer-readonly-type): add support for mapped types 

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/settings.yml
This PR configures the github settings in code as well as setting the issues and PR templates.
- [settings](https://probot.github.io/apps/settings/)
Note: @jonaskello you'll need to install these for the repo.
> configure github settings

- README.md
- docs/rules/prefer-tacit.md
- src/configs/all.ts
- src/configs/stylitic.ts
- src/index.ts
- src/rules/index.ts
- src/rules/prefer-tacit.ts
- src/util/rule.ts
- src/util/typeguard.ts
- tests/configs.test.ts
- tests/rules/prefer-tacit.test.ts
Fix #154 
TODO:
[x] Detect the wrapping function passing all it's parameters to the wrapped function.
[x] Handle the case of the wrapped function's type taking exactly the number of parameters its passed.
[x] Handle the case of the wrapped function taking optional parameters.
[ ] Lots of test.
> Tacit/Point-Free Style rule

- src/index.ts
- tests/index.test.ts
BREAKING CHANGE: removed stylitic ruleset in favor of stylistic ruleset
> chore: remove deprecated stylitic ruleset

- docs/rules/immutable-data.md
- docs/rules/prefer-readonly-type.md
- src/common/ignore-options.ts
- src/configs/functional-lite.ts
- src/rules/immutable-data.ts
- src/util/typeguard.ts
- tests/rules/immutable-data.test.ts
- tests/rules/prefer-readonly-type.test.ts
> feat(immutable-data): add option "ignoreClass"

- .eslintrc.json
- docs/rules/no-conditional-statement.md
- src/rules/no-conditional-statement.ts
- src/util/typeguard.ts
- tests/rules/no-conditional-statement.test.ts
> support never-returning functions for option allowReturningBranches

- src/rules/prefer-readonly-type.ts
- tests/rules/prefer-readonly-type.test.ts
> fix(prefer-readonly-type): computed property fixer

- src/rules/prefer-tacit.ts
> fix(prefer-tacit): cannot read property 'type' of undefined

- docs/rules/no-return-void.md
- src/rules/no-return-void.ts
- src/util/typeguard.ts
- tests/rules/no-return-void.test.ts
> feat(no-return-void): add option to allow for checking implicit return types

- .github/workflows/dependabot-automerge.yml
Fixes: #253
Let dependabot automerge
> Use pull_request_target

- src/rules/no-conditional-statement.ts
- src/util/typeguard.ts
- tests/rules/no-conditional-statement.test.ts
> fix(no-conditional-statement): branch with break/continue statements now treated as returning branch

- docs/rules/no-let.md
- src/rules/no-let.ts
- src/util/tree.ts
- src/util/typeguard.ts
- tests/rules/no-let/es6/valid.ts
> feat(no-let): add option to allow lets inside of for loop initializers

- .releaserc
- package.json
- src/util/rule.ts
- yarn.lock
> fix: rules having broken links to docs

- package.json
- yarn.lock
Reverts jonaskello/eslint-plugin-functional#328
> Revert "build(deps-dev): bump chalk from 4.1.2 to 5.0.0"

- docs/rules/no-throw-statement.md
- src/rules/no-throw-statement.ts
- src/util/tree.ts
- tests/rules/no-throw-statement/es7/index.ts
- tests/rules/no-throw-statement/es7/invalid.ts
- tests/rules/no-throw-statement/es7/valid.ts
- tests/rules/no-throw-statement/index.test.ts
> feat(no-throw-statement): add an option to allow throw statements within async functions

- package.json
- yarn.lock
> build(deps): update deepmerge-ts

- package.json
- src/configs/all.ts
- src/configs/no-mutations.ts
- src/rules/enforce-type-declaration-immutableness.ts
- src/rules/index.ts
- src/util/node-types.ts
- src/util/rule.ts
- tests/rules/enforce-type-declaration-immutableness/index.test.ts
- tests/rules/enforce-type-declaration-immutableness/ts/index.ts
- tests/rules/enforce-type-declaration-immutableness/ts/invalid.ts
- tests/rules/enforce-type-declaration-immutableness/ts/valid.ts
- yarn.lock
Closes #259
Closes #317
Re #153
Supersedes the other readonly rework PRs.
> feat(enforce-type-declaration-immutableness): create rule

- docs/rules/functional-parameters.md
- src/configs/lite.ts
- src/configs/recommended.ts
- src/rules/functional-parameters.ts
- src/util/tree.ts
- tests/rules/functional-parameters/es3/invalid.ts
- tests/rules/functional-parameters/es3/valid.ts
- tests/rules/functional-parameters/es6/invalid.ts
- tests/rules/functional-parameters/es6/valid.ts
> feat(functional-parameters): add option to allow lambda functions

- src/rules/prefer-tacit.ts
- tests/rules/prefer-tacit/es6/invalid.ts
- tests/rules/prefer-tacit/es6/valid.ts
- tests/rules/prefer-tacit/ts/invalid.ts
- tests/rules/prefer-tacit/ts/valid.ts
> fix(prefer-tacit): handling of member expressions and be more strict with optional parameters

- src/rules/no-expression-statements.ts
- src/utils/type-guards.ts
- tests/rules/no-expression-statement/es6/index.ts
- tests/rules/no-expression-statement/es6/invalid.ts
- tests/rules/no-expression-statement/es6/valid.ts
- tests/rules/no-expression-statement/index.test.ts
> fix(no-expression-statements): allow yield expressions

- docs/rules/prefer-immutable-types.md
> docs: fix typo in docs/rules/prefer-immutable-types.md

- GETTING_STARTED.md
- README.md
- docs/rules/immutable-data.md
- docs/rules/no-conditional-statements.md
- docs/rules/no-expression-statements.md
- docs/rules/no-mixed-types.md
- docs/rules/no-return-void.md
- docs/rules/prefer-immutable-types.md
- docs/rules/prefer-property-signatures.md
- docs/rules/prefer-readonly-type.md
- docs/rules/prefer-tacit.md
- docs/rules/readonly-type.md
- docs/rules/type-declaration-immutability.md
- src/configs/disable-type-checked.ts
- src/index.ts
- src/rules/immutable-data.ts
- src/rules/no-conditional-statements.ts
- src/rules/no-expression-statements.ts
- src/rules/no-mixed-types.ts
- src/rules/no-return-void.ts
- src/rules/prefer-immutable-types.ts
- src/rules/prefer-property-signatures.ts
- src/rules/prefer-readonly-type.ts
- src/rules/prefer-tacit.ts
- src/rules/readonly-type.ts
- src/rules/type-declaration-immutability.ts
> docs: update getting started for JS only

- src/rules/immutable-data.ts
- tests/rules/immutable-data/ts/array/valid.ts
> fix(immutable-data): handle immediate mutation of arrays generated from strings
